name    'rchrd2-dokku'
version '0.0.1'
source 'https://github.com/rchrd2/puppet-dokku'
author 'rchrd2'
license 'MIT'
summary 'Puppet module for Dokku'
description 'Puppet module for Dokku'
project_page 'https://github.com/rchrd2/puppet-dokku'

## Add dependencies, if any:
dependency 'puppetlabs/git', '>= 0'
dependency 'puppetlabs/vcsrepo', '>= 0'
dependency 'puppetlabs/apt', '>= 0'
dependency 'puppetlabs/concat', '>= 0'
dependency 'puppetlabs/stdlib', '>= 0'